NumPy ndarray Object

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:

arr1 = np.array(42)
print(arr1)
# 1D
arr2 = np.array([1, 2, 3, 4, 5])
print(arr2)
# 2D
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3)
#3D
arr4 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr4)

42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Indexing

In [3]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [4]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [5]:
print('2nd element on 1st row: ', arr3[0, 1])

2nd element on 1st row:  2


In [6]:
print('3rd element on 2nd row: ', arr3[1, 2])

3rd element on 2nd row:  6


In [7]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print('3rd element on 2nd row:',arr[0, 1, 2])

3rd element on 2nd row: 6


In [8]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


Slicing

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [11]:
# Return every other element from the entire array
print(arr[::2])

[1 3 5 7]


In [12]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [13]:
# From both elements, return index 2
print(arr[0:2, 2])

[3 8]


In [14]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [15]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [16]:
# Create an array with data type string:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [17]:
# Change data type from float to integer by using 'i' as parameter value:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')

print(arr.dtype)
print(newarr)
print(newarr.dtype)

float64
[1 2 3]
int32


Copy and View

In [18]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy() #The copy SHOULD NOT be affected by the changes made to the original array.
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [19]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view() #The view SHOULD be affected by the changes made to the original array.
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [20]:
# Joining Array

In [21]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)


[1 2 3 4 5 6]


In [22]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [23]:
arr = np.hstack((arr1, arr2))#Alonh Rows

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [24]:
arr = np.vstack((arr1, arr2))#Along Columns

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [25]:
arr = np.dstack((arr1, arr2))#Along Depth

print(arr)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [26]:
# Searching
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [27]:
# Sorting
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [28]:
# Generate a random integer from 0 to 100:

from numpy import random

x = random.randint(100)

print(x)

86


In [29]:
# The random module's rand() method returns a random float between 0 and 1.
x = random.rand()

print(x)

0.6991874758405414


In [30]:
# The randint() method takes a size parameter where you can specify the shape of an array.
# Generate a 1-D array containing 5 random integers from 0 to 100:

x=random.randint(100, size=(5))

print(x)


[29 56 92 92 52]


In [31]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

x = random.randint(100, size=(3, 5))

print(x)

[[10 11 32 83 39]
 [25 36 37 37 75]
 [25 19 66 32 39]]


In [32]:
# The rand() method also allows you to specify the shape of the array.
# Generate a 1-D array containing 5 random floats:

x = random.rand(5)

print(x)

[0.38520555 0.03240133 0.18155079 0.91989211 0.24038634]


In [33]:
x = random.rand(3, 5)

print(x)

[[0.82664594 0.72559821 0.00166161 0.91024995 0.83568114]
 [0.31752772 0.22844977 0.8295323  0.38322939 0.03335859]
 [0.67164429 0.54170247 0.62799242 0.19002176 0.81715405]]


In [34]:
# Generate Random Number From Array
# The choice() method allows you to generate a random value based on an array of values.
# The choice() method takes an array as a parameter and randomly returns one of the values.
# Return one of the values in an array:


x = random.choice([3, 5, 7, 9])

print(x)

7


In [35]:
# NumPy ufuncs
# ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.


In [36]:
# With ufunc, we can use the add() function:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)


[ 5  7  9 11]


In [37]:
# Creating Custom Function
import numpy as np

def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [38]:
# Airthmetic Operations
import numpy as np

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr1 = np.add(arr1, arr2)
newarr2 = np.subtract(arr1, arr2)
newarr3 = np.multiply(arr1, arr2)
newarr4 = np.divide(arr1, arr2)
print(newarr1)
print(newarr2)
print(newarr3)
print(newarr4)

[30 32 34 36 38 40]
[-10 -10 -10 -10 -10 -10]
[200 231 264 299 336 375]
[0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6       ]


In [39]:
# GCD
import numpy as np

num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)

3


In [40]:
arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)


4
